from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from typing import Any
from urllib.error import HTTPError
from urllib.request import Request, urlopen


DEFAULT_METABASE_URL = "http://localhost:3000"


@dataclass
class CardSpec:
    name: str
    query: str
    display: str
    row: int
    col: int
    size_x: int
    size_y: int
    visualization_settings: dict[str, Any]


class MetabaseClient:
    def __init__(self, base_url: str) -> None:
        self.base_url = base_url.rstrip("/")
        self.session_id: str | None = None

    def request(self, method: str, path: str, payload: dict[str, Any] | None = None) -> Any:
        headers = {"Content-Type": "application/json"}
        if self.session_id:
            headers["X-Metabase-Session"] = self.session_id

        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        request = Request(f"{self.base_url}{path}", data=data, headers=headers, method=method)
        try:
            with urlopen(request, timeout=60) as response:
                content = response.read().decode("utf-8")
                return json.loads(content) if content else None
        except HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"{method} {path} failed: HTTP {exc.code}: {body}") from exc

    def login(self, email: str, password: str) -> None:
        result = self.request("POST", "/api/session", {"username": email, "password": password})
        self.session_id = result["id"]

    def list_databases(self) -> list[dict[str, Any]]:
        result = self.request("GET", "/api/database")
        if isinstance(result, dict) and "data" in result:
            return result["data"]
        if isinstance(result, list):
            return result
        return []

    def ensure_clickhouse_database(self) -> int:
        for database in self.list_databases():
            if database.get("name") == "Sales ADS ClickHouse":
                return int(database["id"])

        payload = {
            "name": "Sales ADS ClickHouse",
            "engine": "clickhouse",
            "details": {
                "host": "clickhouse",
                "port": 8123,
                "dbname": "sales_ads",
                "user": "sales_user",
                "password": "sales_password",
                "ssl": False,
            },
            "is_full_sync": True,
            "is_on_demand": False,
            "schedules": {},
        }
        database = self.request("POST", "/api/database", payload)
        database_id = int(database["id"])
        try:
            self.request("POST", f"/api/database/{database_id}/sync_schema")
        except RuntimeError as exc:
            print(f"Schema sync request skipped: {exc}")
        return database_id

    def find_collection_id(self, name: str) -> int | None:
        result = self.request("GET", "/api/collection")
        collections = result.get("data", result) if isinstance(result, dict) else result
        for collection in collections:
            if collection.get("name") == name:
                return int(collection["id"])
        return None

    def ensure_collection(self, name: str, description: str) -> int:
        collection_id = self.find_collection_id(name)
        if collection_id is not None:
            return collection_id
        collection = self.request("POST", "/api/collection", {"name": name, "description": description})
        return int(collection["id"])

    def create_card(self, database_id: int, collection_id: int, spec: CardSpec) -> int:
        payload = {
            "name": spec.name,
            "description": "Generated by scripts/create_metabase_dashboard.py",
            "display": spec.display,
            "dataset_query": {
                "database": database_id,
                "type": "native",
                "native": {"query": spec.query},
            },
            "visualization_settings": spec.visualization_settings,
            "collection_id": collection_id,
        }

        for card in self.list_cards():
            if card.get("name") == spec.name and card.get("collection_id") == collection_id:
                self.request("PUT", f"/api/card/{int(card['id'])}", payload)
                return int(card["id"])

        card = self.request("POST", "/api/card", payload)
        return int(card["id"])

    def list_cards(self) -> list[dict[str, Any]]:
        result = self.request("GET", "/api/card")
        if isinstance(result, dict):
            return result.get("data") or result.get("value") or []
        if isinstance(result, list):
            return result
        return []

    def list_dashboards(self) -> list[dict[str, Any]]:
        result = self.request("GET", "/api/dashboard")
        if isinstance(result, dict):
            return result.get("data") or result.get("value") or []
        if isinstance(result, list):
            return result
        return []

    def ensure_dashboard(self, collection_id: int) -> int:
        for dashboard in self.list_dashboards():
            if dashboard.get("name") == "Sales Analytics Dashboard" and dashboard.get("collection_id") == collection_id:
                return int(dashboard["id"])

        payload = {
            "name": "Sales Analytics Dashboard",
            "description": "Daily sales, conversion, LTV, contribution, and abnormal refund metrics.",
            "collection_id": collection_id,
        }
        dashboard = self.request("POST", "/api/dashboard", payload)
        return int(dashboard["id"])

    def update_dashboard_cards(self, dashboard_id: int, card_layouts: list[tuple[int, CardSpec]]) -> None:
        dashboard = self.request("GET", f"/api/dashboard/{dashboard_id}")
        existing_dashcards = dashboard.get("dashcards", [])
        dashcard_by_card_id = {}
        for dashcard in existing_dashcards:
            card = dashcard.get("card") or {}
            card_id = dashcard.get("card_id") or card.get("id")
            if card_id is not None:
                dashcard_by_card_id[int(card_id)] = dashcard

        cards = []
        next_temp_id = -1
        for card_id, spec in card_layouts:
            existing = dashcard_by_card_id.get(card_id)
            dashcard_id = int(existing["id"]) if existing else next_temp_id
            if not existing:
                next_temp_id -= 1
            cards.append(
                {
                    "id": dashcard_id,
                    "card_id": card_id,
                    "row": spec.row,
                    "col": spec.col,
                    "size_x": spec.size_x,
                    "size_y": spec.size_y,
                    "parameter_mappings": existing.get("parameter_mappings", []) if existing else [],
                    "series": existing.get("series", []) if existing else [],
                }
            )

        self.request("PUT", f"/api/dashboard/{dashboard_id}/cards", {"cards": cards, "tabs": []})


def card_specs() -> list[CardSpec]:
    return [
        CardSpec(
            name="Daily Sales Trend",
            display="line",
            row=0,
            col=0,
            size_x=24,
            size_y=7,
            query="""
SELECT
  sale_date,
  sales_amount
FROM ads_daily_sales
ORDER BY sale_date
""".strip(),
            visualization_settings={
                "graph.dimensions": ["sale_date"],
                "graph.metrics": ["sales_amount"],
            },
        ),
        CardSpec(
            name="Channel Conversion Rate",
            display="bar",
            row=7,
            col=0,
            size_x=10,
            size_y=6,
            query="""
SELECT
  channel_name,
  round(conversion_rate * 100, 2) AS conversion_rate_pct,
  visits,
  paid_orders
FROM ads_channel_conversion
ORDER BY conversion_rate DESC
""".strip(),
            visualization_settings={
                "graph.dimensions": ["channel_name"],
                "graph.metrics": ["conversion_rate_pct"],
            },
        ),
        CardSpec(
            name="Repeat Rate",
            display="scalar",
            row=7,
            col=10,
            size_x=5,
            size_y=3,
            query="""
SELECT
  round(repeat_purchase_rate * 100, 2) AS repeat_purchase_rate_pct
FROM ads_repeat_purchase
""".strip(),
            visualization_settings={
                "scalar.field": "repeat_purchase_rate_pct",
                "scalar.suffix": "%",
            },
        ),
        CardSpec(
            name="Top 10 User LTV",
            display="table",
            row=13,
            col=0,
            size_x=12,
            size_y=6,
            query="""
SELECT
  ltv_rank,
  user_name,
  province,
  city,
  paid_orders,
  total_amount
FROM ads_user_ltv
ORDER BY ltv_rank
LIMIT 10
""".strip(),
            visualization_settings={},
        ),
        CardSpec(
            name="Top Product Contribution",
            display="table",
            row=13,
            col=12,
            size_x=12,
            size_y=6,
            query="""
SELECT
  product_id,
  product_name,
  category,
  sales_amount,
  round(contribution_rate * 100, 3) AS contribution_pct
FROM ads_product_contribution
ORDER BY contribution_rate DESC
LIMIT 10
""".strip(),
            visualization_settings={},
        ),
        CardSpec(
            name="Abnormal Refund Rate by Category",
            display="bar",
            row=7,
            col=15,
            size_x=9,
            size_y=6,
            query="""
SELECT
  category,
  round(refund_rate * 100, 2) AS refund_rate_pct,
  abnormal_flag
FROM ads_abnormal_refund
ORDER BY abnormal_flag DESC, refund_rate DESC
""".strip(),
            visualization_settings={
                "graph.dimensions": ["category"],
                "graph.metrics": ["refund_rate_pct"],
            },
        ),
        CardSpec(
            name="Realtime Event Count",
            display="scalar",
            row=19,
            col=0,
            size_x=6,
            size_y=3,
            query="""
SELECT
  count() AS realtime_event_count
FROM rt_order_events
WHERE ingested_at >= now() - INTERVAL 24 HOUR
""".strip(),
            visualization_settings={"scalar.field": "realtime_event_count"},
        ),
        CardSpec(
            name="Realtime Sales Amount",
            display="scalar",
            row=19,
            col=6,
            size_x=6,
            size_y=3,
            query="""
SELECT
  round(sumIf(total_amount, event_type = 'order_paid'), 2) AS realtime_sales_amount
FROM rt_order_events
WHERE ingested_at >= now() - INTERVAL 24 HOUR
""".strip(),
            visualization_settings={
                "scalar.field": "realtime_sales_amount",
                "scalar.suffix": " CNY",
            },
        ),
        CardSpec(
            name="Realtime Event Type Mix",
            display="bar",
            row=19,
            col=12,
            size_x=12,
            size_y=5,
            query="""
SELECT
  event_type,
  count() AS events
FROM rt_order_events
WHERE ingested_at >= now() - INTERVAL 24 HOUR
GROUP BY event_type
ORDER BY events DESC
""".strip(),
            visualization_settings={
                "graph.dimensions": ["event_type"],
                "graph.metrics": ["events"],
            },
        ),
        CardSpec(
            name="Latest Realtime Order Events",
            display="table",
            row=24,
            col=0,
            size_x=24,
            size_y=6,
            query="""
SELECT
  formatDateTime(event_time, '%Y-%m-%d %H:%i:%S', 'Asia/Shanghai') AS event_time_local_text,
  formatDateTime(ingested_at, '%Y-%m-%d %H:%i:%S', 'Asia/Shanghai') AS ingested_at_local_text,
  event_type,
  order_id,
  user_id,
  channel_id,
  total_amount
FROM rt_order_events
ORDER BY ingested_at DESC
LIMIT 20
""".strip(),
            visualization_settings={},
        ),
        CardSpec(
            name="Minute Sales Trend",
            display="line",
            row=30,
            col=0,
            size_x=12,
            size_y=6,
            query="""
SELECT
  formatDateTime(event_minute, '%Y-%m-%d %H:%i', 'Asia/Shanghai') AS event_minute_local_text,
  sales_amount
FROM rt_order_minute_summary
WHERE event_minute >= now() - INTERVAL 24 HOUR
ORDER BY event_minute
""".strip(),
            visualization_settings={
                "graph.dimensions": ["event_minute_local_text"],
                "graph.metrics": ["sales_amount"],
            },
        ),
        CardSpec(
            name="Minute Event Trend",
            display="line",
            row=30,
            col=12,
            size_x=12,
            size_y=6,
            query="""
SELECT
  formatDateTime(event_minute, '%Y-%m-%d %H:%i', 'Asia/Shanghai') AS event_minute_local_text,
  event_count,
  paid_order_count,
  refund_count,
  cancel_count
FROM rt_order_minute_summary
WHERE event_minute >= now() - INTERVAL 24 HOUR
ORDER BY event_minute
""".strip(),
            visualization_settings={
                "graph.dimensions": ["event_minute_local_text"],
                "graph.metrics": ["event_count", "paid_order_count", "refund_count", "cancel_count"],
            },
        ),
        CardSpec(
            name="Minute Realtime Summary",
            display="table",
            row=36,
            col=0,
            size_x=24,
            size_y=6,
            query="""
SELECT
  formatDateTime(event_minute, '%Y-%m-%d %H:%i', 'Asia/Shanghai') AS event_minute_local_text,
  event_count,
  paid_order_count,
  sales_amount,
  refund_count,
  cancel_count,
  formatDateTime(last_ingested_at, '%Y-%m-%d %H:%i:%S', 'Asia/Shanghai') AS last_ingested_at_local_text
FROM rt_order_minute_summary
ORDER BY event_minute DESC
LIMIT 30
""".strip(),
            visualization_settings={},
        ),
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create Metabase sales analytics dashboard.")
    parser.add_argument("--url", default=DEFAULT_METABASE_URL)
    parser.add_argument("--email", required=True, help="Metabase admin email.")
    parser.add_argument("--password", required=True, help="Metabase admin password.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    client = MetabaseClient(args.url)
    client.login(args.email, args.password)

    database_id = client.ensure_clickhouse_database()
    collection_id = client.ensure_collection(
        "Sales Analytics",
        "Generated dashboards and questions for the local sales analytics project.",
    )
    dashboard_id = client.ensure_dashboard(collection_id)

    card_layouts = []
    for spec in card_specs():
        card_id = client.create_card(database_id, collection_id, spec)
        card_layouts.append((card_id, spec))
        print(f"Created card {card_id}: {spec.name}")

    client.update_dashboard_cards(dashboard_id, card_layouts)
    print(f"Dashboard created: {args.url.rstrip('/')}/dashboard/{dashboard_id}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(exc, file=sys.stderr)
        sys.exit(1)
